build: TCPIPSimulator
	
TCPIPSimulator: main.cpp
	g++ -O2 main.cpp -o TCPIPSimulator -Wall -Wextra -Wdisabled-optimization \
	-Wcast-qual -Wcast-align -Wpointer-arith -Wundef -Wredundant-decls \
	-Wunused-macros -Wswitch-default -Wconversion -Wfloat-equal \
	-Wold-style-cast -Weffc++
	
clean:
	rm -vf TCPIPSimulator
